name: flutter_ringtone_manager
description: "RingtoneManager (RingtonePlayer) plugin provides access to ringtones, notification,
and other types of sounds for both Android & iOS platforms. A perfect player for short sounds."
version: 1.1.2
homepage: https://github.com/trdevendran/flutter_ringtone_manager.git

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_ringtone_manager
        pluginClass: FlutterRingtoneManagerPlugin
      ios:
        pluginClass: FlutterRingtoneManagerPlugin
      macos:
        pluginClass: FlutterRingtoneManagerPlugin
      web:
        pluginClass: FlutterRingtoneManagerWeb
        fileName: flutter_ringtone_manager_web.dart
